import { AuthProvider } from '@/context/AuthContext';
import '../app/globals.css';

export const metadata = {
  title: 'Ev 2',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <AuthProvider>
          {children}
       </AuthProvider>
      </body>
    </html>
  )
}
