import React from 'react';
import { AuthProvider } from '@/context/AuthContext';
import '../app/globals.css';
import { Footer } from './Footer';

export const metadata = {
  title: 'Ev 2',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <AuthProvider>
          <div className='mb-[67px]'>
          {children}
          </div>
          <Footer />
       </AuthProvider>
      </body>

    </html>
  )
}
