const TDocumento = ({
  RECURSO: 'documento',
  TABELA: 'tb_documento',
  VIEW: 'vw_documento',
  FIELD1: 'dc_id',
  FIELD2: 'dc_idempresa',
  FIELD3: 'dc_descricao',
  FIELD4: 'dc_idcartao',
  FIELD5: 'dc_tipo',
  FIELD6: 'dc_receber',
  FIELD7: 'dc_caixa',
  FIELD8: 'dc_pagar',
  FIELD9: 'dc_venda',
  FIELD10: 'dc_vezes',
  FIELD11: 'dc_intervalo',
  FIELD12: 'dc_modalidade',
  FIELD13: 'dc_idcontabancaria',
  FIELD14: 'dc_venctoprimeiraparcela',
  FIELD15: 'dc_usarvezespadrao',
  FIELD16: 'dc_idformapagtonfe',
  FIELD17: 'dc_histdtcadastro',
  FIELD18: 'dc_histuscadastro',
  FIELD19: 'dc_histdtalteracao',
  FIELD20: 'dc_histusalteracao',
  FIELD21: 'dc_histdtdeletado',
  FIELD22: 'dc_histusdeletado',
  FIELD23: 'dc_deletado',
  FIELD25: 'dc_quantparcelapadrao',
  FIELD100: 'dc_tipodesc',
  FIELD101: 'dc_descartao',
  FIELD102: 'dc_descformapagtonfe'
});
  
export { TDocumento };